### ISSUE TITLE
FlatDict error

### ISSUE THREAD

**Issue by BugUser0815** [pecheur/toolchain-host#9]
taskgen/task.py", line 83, in variants

flat = flatdict.FlatDict(self,None, dict,True)
TypeError: __init__() takes from 1 to 3 positional arguments but 5 were given

FlatDict 2.0.1

While executing ./taskgen-cli run -d -t test.Problem0 10.200.40.11

Replacing
#flat = flatdict.FlatDict(self,None, dict,True)
with
flat = flatdict.FlatDict(self)
solves the problem.

**Comment by pecheur** [comment]
There was a difference in the versions from github and pypi.python.org, which is used by pip. This error is fixed with  e3a41f3.

Please run `pip3 install --user -r ./requirements.txt` again, if this error occurs.
